eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-netflix-app:8761/eureka
#      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true