version: '3.3'

services:
    db:
      image: mysql:latest
      container_name: mysql-db2   
      environment:
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - "3366:3306"
      restart: always

    aggregator-service:                        #it is just a name, which will be used only in this file.
      image: aggregator              #name of the image after dockerfile executes
      container_name: aggregator-app  #name of the container created from docker image
      build:
        context: ./aggregator                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:    
        - "3387:8080"                #docker containter port with your os port
      restart: always
        
      depends_on:    
        - eureka-service     
          
    #service 3: definition of your spring-boot app 
    customerservice:                        #it is just a name, which will be used only in this file.
      image: temperature              #name of the image after dockerfile executes
      container_name: temperature-app  #name of the container created from docker image
      build:
        context: ./temp                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:     
        - "3388:8081"                #docker containter port with your os port
      restart: always
        
      depends_on:                           #define dependencies of this app
        - db
        - eureka-service                                #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/Test?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: Tomeek
        SPRING_DATASOURCE_PASSWORD: ty_tomek

    secondservice:                        #it is just a name, which will be used only in this file.
      image: humidity              #name of the image after dockerfile executes
      container_name: humidity-app  #name of the container created from docker image
      build:
        context: ./humidity                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:    
        - "3389:8080"                #docker containter port with your os port
      restart: always
        
      depends_on:                           #define dependencies of this app
        - db    
        - eureka-service                            #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/Test?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: Tomeek
        SPRING_DATASOURCE_PASSWORD: ty_tomek

    eureka-service:                        #it is just a name, which will be used only in this file.
      image: eureka-netflix              #name of the image after dockerfile executes
      container_name: eureka-netflix-app #name of the container created from docker image
      build:
        context: ./eureka                          #docker file path (. means root directory)
        dockerfile: Dockerfile                    #docker file name
        network: host             
      ports:
        - "8761:8761"                 #docker containter port with your os port
      restart: always